#! /bin/sh

KEYWORDS="dataset,large_res,sample_res,delta,opt_param,epsilon,theta,initial_sample_size,sample_size_avg,sample_size_max,sample_size_min,sample_size_stdev,iteration_avg,iteration_max,iteration_min,iteration_stdev,sampling_time_avg,sampling_time_max,sampling_time_min,sampling_time_stdev,stopcond_time_avg,stopcond_time_max,stopcond_time_min,stopcond_time_stdev,runtime_avg,runtime_max,runtime_min,runtime_stdev,mining_time_avg,mining_time_max,mining_time_min,mining_time_stdev,total_time_avg,total_time_max,total_time_min,total_time_stdev,orig_FIs,intersection_avg,intersection_max,intersection_min,intersection_stdev,false_negs_avg,false_negs_max,false_negs_min,false_negs_stdev,false_pos_avg,false_pos_max,false_pos_min,false_pos_stdev,non_acceptable_false_pos_avg,non_acceptable_false_pos_max,non_acceptable_false_pos_min,non_acceptable_false_pos_stdev,jaccard_avg,jaccard_max,jaccard_min,jaccard_stdev,wrong_eps_avg,wrong_eps_max,wrong_eps_min,wrong_eps_stdev,max_abs_err_avg,max_abs_err_max,max_abs_err_min,max_abs_err_stdev,avg_abs_err_avg,avg_abs_err_max,avg_abs_err_min,avg_abs_err_stdev,avg_rel_err_avg,avg_rel_err_max,avg_rel_err_min,avg_rel_err_stdev"

for ds in `ls *vars.sh`; do
	sh experiment.sh collect ${KEYWORDS} $ds
done
